branches:
  only:
    - master
    - travis


language: generic


matrix:
  include:
    - os: linux
      dist: bionic
      env:
        - CI_DEPEND_DIR=https://raw.githubusercontent.com/zhi-wang/ci-depend/master/xenial


before_install:
  - sudo apt-get install gfortran cmake


script:
  - gfortran -v
  - g++ -v
  - cmake --version
  - echo $HOME
  - echo $PWD


# fftw
  - mkdir build
  - cd build
  - mkdir -p fftw/include
  - curl $CI_DEPEND_DIR/fftw/include/fftw3.h -o fftw/include/fftw3.h

  - mkdir -p fftw/lib
  - cd fftw/lib
  - curl $CI_DEPEND_DIR/fftw/lib/libfftw3.a          -o libfftw3.a
  - curl $CI_DEPEND_DIR/fftw/lib/libfftw3_threads.a  -o libfftw3_threads.a
  - curl $CI_DEPEND_DIR/fftw/lib/libfftw3f.a         -o libfftw3f.a
  - curl $CI_DEPEND_DIR/fftw/lib/libfftw3f_threads.a -o libfftw3f_threads.a
  - cd ../../..


# libtinker.a
  - cd tinker
  - git submodule update --init
  - cd ..
  - cp -r tinker build
  - cd build/tinker/source
  - curl $CI_DEPEND_DIR/tinker-b606a90b/Makefile -o Makefile
  - make libtinker.a -j2
  - cd ../..


# test tinker.gpu
  - opt=release host=1 prec=d fftw_dir=fftw tinker_dir=tinker/source cmake ..
  - make test -j2
